version : "2"
services: 
  php-fpm_service:
    container_name: php-fpm_container
    build: ./docker/php
    volumes:
      - ./app:/app
    restart: always

  nginx_service:
    container_name: nginx_container
    build: ./docker/nginx
    volumes:
       - ./app:/app
       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
       - "8080:80"
    restart: always    
    links:
       - "php-fpm_service"